version: '3'

services:
  carnage:
    image: carnage:latest
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    ports:
      - 5050:5050
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: carnage
      POSTGRES_PASSWORD: carnage
      POSTGRES_DB: carnage

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carnage.world
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pgadmin-data:
