# A Docker Compose must always start with the version tag.
# We use '3' because it's the last version.
version: '3'

services:
  carnage:
    image: carnage:latest
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    ports:
      - 5050:5050
    env_file:
      - .env
    depends_on:
      - database

  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: postgres:latest
    ports:
      - 5432:5432

    # The `env_file` tag allows us to declare an environment file
    env_file:
      - .env.db # The name of your environment file (the one at the repository root)
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carnage.rip
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
