[build-system]
requires = ["poetry-core>=1.0.4"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ["py310"]
exclude = "((.eggs | .git | .pytest_cache | build | dist))"

[tool.poetry]
name = "carnage"
version = "0.0.0"
description = " A hardcore game"
authors = ["Rodolfo Olivieri <rodolfo.olivieri3@gmail.com>"]
maintainers = ["Rodolfo Olivieri <rodolfo.olivieri3@gmail.com>"]
homepage = "https://github.com/r0x0d/carnage"
repository = "https://github.com/r0x0d/carnage"
documentation = "https://github.com/r0x0d/carnage"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
keywords = ["carnage", "game", "hardcore"]
include = ["LICENSE.txt", "README.md"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "1.8.1"
argon2-cffi = "21.3.0"
authlib = "1.1.0"
cryptography = "38.0.1"
fastapi = "0.85.1"
itsdangerous = "2.1.2"
psycopg2-binary = "2.9.4"
pydantic = "1.10.2"
sqlalchemy = "1.4.42"
uvicorn = { version = "0.19.0", extras = ["standard"]}
httpx = "0.23.0"

[tool.poetry.dev-dependencies]
anyio = "3.6.2"
covdefaults = "2.2.0"
coverage = "6.5.0"
pytest = "7.1.3"
pytest-env = "0.7.0"
python-dotenv = "0.21.0"
tox = "^3.26.0"

[tool.poetry.scripts]
carnage = "carnage.__main__:main"


[tool.coverage.run]
plugins = ["covdefaults"]
source = ["carnage"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
ignore_errors = true
