[build-system]
requires = ["poetry-core>=1.0.4"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py311"]
exclude = "((.eggs | .git | .pytest_cache | build | dist))"

[tool.poetry]
name = "carnage"
version = "0.0.0"
description = " A hardcore game"
authors = ["Rodolfo Olivieri <rodolfo.olivieri3@gmail.com>"]
maintainers = ["Rodolfo Olivieri <rodolfo.olivieri3@gmail.com>"]
homepage = "https://github.com/r0x0d/carnage"
repository = "https://github.com/r0x0d/carnage"
documentation = "https://github.com/r0x0d/carnage"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
keywords = ["carnage", "game", "hardcore"]
include = ["LICENSE.txt", "README.md"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
alembic = "1.8.1"
authlib = "1.2.0"
cryptography = "38.0.4"
fastapi = "0.88.0"
itsdangerous = "2.1.2"
psycopg2-binary = "2.9.5"
pydantic = { version = "1.10.2", extras = ["email"] }
sqlalchemy = "1.4.44"
uvicorn = { version = "0.20.0", extras = ["standard"] }
httpx = "0.23.1"
pydantic-sqlalchemy = "0.0.9"
rich = "12.6.0"
Jinja2 = "3.1.2"
python-jose = { version = "3.3.0", extras = ["cryptography"] }

[tool.poetry.dev-dependencies]
anyio = "3.6.2"
covdefaults = "2.2.2"
coverage = "6.5.0"
pytest = "7.2.0"
pytest-env = "0.8.1"
tox = "4.0.0"
black = { version = "22.10.0", allow-prereleases = true }

[tool.poetry.scripts]
carnage = "carnage.__main__:main"


[tool.coverage.run]
plugins = ["covdefaults"]
source = ["carnage"]
omit = ["carnage/api/routes/debug.py"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
ignore_errors = true
